/*
 * generated by Xtext
 */
package de.morknet.ui.contentassist

import de.morknet.ui.contentassist.AbstractMDSC3ProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MDSC3ProposalProvider extends AbstractMDSC3ProposalProvider {
}
