/*
 * generated by Xtext
 */
package de.morknet.mdsc3;

import org.eclipse.xtext.conversion.IValueConverterService;

import de.morknet.mdsc3.converter.MdscValueConverters;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class MDSC3RuntimeModule extends de.morknet.mdsc3.AbstractMDSC3RuntimeModule
{
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService()
	{
		return MdscValueConverters.class;
	}
}
