/*
 * generated by Xtext
 */
package de.morknet.mdsc3.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class MDSC3ProposalProvider extends de.morknet.mdsc3.ui.contentassist.AbstractMDSC3ProposalProvider {

}
