/*
 * generated by Xtext
 */
package de.morknet.ui;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;

import de.morknet.ui.coloring.SyntaxColoringMapper;
import de.morknet.ui.labeling.MDSC3LabelProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MDSC3UiModule extends de.morknet.ui.AbstractMDSC3UiModule
{
	public MDSC3UiModule(AbstractUIPlugin plugin)
	{
		super(plugin);
	}

	@Override
	public Class<? extends ILabelProvider> bindILabelProvider()
	{
		return MDSC3LabelProvider.class;
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindTokenToAttributeIdMapper()
	{
		return SyntaxColoringMapper.class;
	}
}
